name: Swift Unit Tests

on: push

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v

    # temporarily disabled because YouTube blocked GitHub actions url
    #- name: Run tests
    #  run: swift test -v
